server:
  port: 18081
spring:
  application:
    name: dubbo-service-consumer
  cloud:
    nacos:
      server-addr: localhost:38080
dubbo:
  application:
    name: dubbo-service-consumer
  registry:
    address: 192.168.40.3:38080
    protocol: nacos
  protocol:
    port: 28081
    name: dubbo
  cloud:
    subscribed-services: dubbo-service-provider

